version: '3.8'

services:
  web:
    build: .
    container_name: car_sales_web
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=.
    volumes:
      - .:/car_sales_prediction
    command: uvicorn app:app --host 0.0.0.0 --port 8000
